CREATE DATABASE IF NOT EXISTS projeto;

USE projeto;

CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(100) NOT NULL,
  idade VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS adress (
  user_id INT NOT NULL,
  bairro VARCHAR(100) NOT NULL,
  cep VARCHAR(100) NOT NULL,
  complemento VARCHAR(100) NOT NULL,
  localidade VARCHAR(100) NOT NULL,
  logradouro VARCHAR(100) NOT NULL,
  numero VARCHAR(100) NOT NULL,
  uf VARCHAR(50) NOT NULL,
  PRIMARY KEY(user_id)
);